name: Bicep Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep files
    - name: Deploy to Tenant
      run: >-
        az deployment tenant create
        --name github-mg-deploy
        --location eastus
        -f ${GITHUB_WORKSPACE}/templates/mgs/main.bicep &&
        az deployment tenant create
        --name github-mg-settings-deploy
        --location eastus
        -f ${GITHUB_WORKSPACE}/templates/mg-settings/main.bicep
    - name: Logout
      uses: azure/CLI@v1
      if: always()
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
